-- Example table: customers
CREATE TABLE CUSTOMERS
(
    ID INTEGER NOT NULL,
    NAME D_NAME,
    EMAIL D_EMAIL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE SMALLINT DEFAULT 1
);
