-- Example table: orders
CREATE TABLE ORDERS
(
    ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT D_PRICE,
    STATUS VARCHAR(50) DEFAULT 'PENDING'
);
