-- Example stored procedure: get active customers
SET TERM ^ ;

CREATE PROCEDURE SP_GET_ACTIVE_CUSTOMERS
RETURNS
(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR(100),
    EMAIL VARCHAR(255)
)
AS
BEGIN
    FOR SELECT ID, NAME, EMAIL
        FROM CUSTOMERS
        WHERE IS_ACTIVE = 1
        INTO :CUSTOMER_ID, :CUSTOMER_NAME, :EMAIL
    DO
        SUSPEND;
END^

SET TERM ; ^
